# This is a starter pipeline to handle Gated PRs using GHAzDO. Currently (October 2023) this is not supported out of the box by the product,
# it probably will be supported in the future, this project can be used as a workaround until that time.
# We want to restrict new code going into main and only allow PRs if the new code does not introduce any new CodeQL or Dependency Scanning issues.
# The idea is to set a branch protection policy (for main), forcing this pipeline to succeed before a PR into main can happen.
# The pipeline will run CodeQL and Dependency Scanning on the source branch of the PR. Later, using a PowerShell script, the security alerts of the PR source and target will be compared.
# If there are alerts in the PR source that are not in main, this pipeline will fail.
#
# If new alerts are detected these needs to be analysed using the regular Advanced Security Code Scanning UI.
#  - For Code Scanning, use the filter to the pr branch and fix or dissmiss all the new issues.
#  - For Depenendcy Scanning, use the the link in the pipeline output or PR comment to view/fix or dissmiss all the new issues.
# After that, the PR check CIVerify can be requeued in the PR. Hopefully this time, without any issues.
#
# The script needs a PAT to run (for accessing the REST API). This PAT should be setup as a secret variable for the pipleline (name: GATING_PAT).
# The PAT needs the access right - Advanced Security - Read
#
# More on ADO build verifications: https://learn.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#build-validation

trigger:
- none

pool:
  vmImage: ubuntu-latest

# Variables for CodeQL
variables:
  SourcesFolder: src\main


steps:
# Run CodeQL on this branch (source branch of the PR)
- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    languages: 'javascript'

- task: AdvancedSecurity-Codeql-Autobuild@1
- task: AdvancedSecurity-Dependency-Scanning@1
- task: AdvancedSecurity-Codeql-Analyze@1
  inputs:
    WaitForProcessing: true

# Compair CodeQL / Dependency issues on the PR source branch and main.
# Fail if there are new issues.
- task: PowerShell@2
  displayName: 'CI Gating - verify there are no new security issues introduced in this PR'
  inputs:
    targetType: filePath
    filePath: CIGate.ps1
    pwsh: true # Script requires PS7 (otherwise you will see syntax error - Unexpected token '?' )
  env:
    MAPPED_ADO_PAT: $(GATING_PAT)
