trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: docker run -e GITHUB_ACTIONS=true -e GITHUB_WORKFLOW=1 -v $(Build.SourcesDirectory):/app ghcr.io/psalm/psalm-security-scan 
  displayName: 'Run Psalm Security Scan'
  continueOnError: true

- task: AdvancedSecurity-Publish@1
  inputs:
    SarifsInputDirectory: '$(Build.SourcesDirectory)'
    Category: 'PSALM'